#!/usr/bin/env bash
# Bootstrap this machine with all skills from spiosifidis/my-claude-skills.
#
# Usage (run on any new or existing machine):
#   curl -fsSL https://raw.githubusercontent.com/spiosifidis/my-claude-skills/main/bootstrap.sh | bash
# or, from a local clone:
#   ./bootstrap.sh
#
# Idempotent: safe to re-run any time; re-running also picks up new/updated skills.
set -euo pipefail

REPO="spiosifidis/my-claude-skills"

if ! command -v npx >/dev/null 2>&1; then
  echo "error: npx not found — install Node.js first (https://nodejs.org)" >&2
  exit 1
fi

echo "==> Installing/syncing all skills from ${REPO} into user scope (~/.claude/skills)..."
npx --yes skills add "${REPO}" -s '*' -g -y

# Make skill invocation reliable: a one-line nudge in the global CLAUDE.md so
# every session checks installed skills before answering. Guarded so re-runs
# never duplicate it.
CLAUDE_MD="${HOME}/.claude/CLAUDE.md"
MARKER="<!-- my-claude-skills:invoke-skills -->"
if ! grep -qF "${MARKER}" "${CLAUDE_MD}" 2>/dev/null; then
  mkdir -p "${HOME}/.claude"
  {
    echo ""
    echo "${MARKER}"
    echo "Before responding to any request, check whether an installed skill in ~/.claude/skills applies (see the using-superpowers skill). If one plausibly applies, invoke it with the Skill tool before doing anything else."
  } >> "${CLAUDE_MD}"
  echo "==> Added skill-invocation reminder to ${CLAUDE_MD}"
else
  echo "==> Skill-invocation reminder already present in ${CLAUDE_MD}"
fi

# Keep this machine in sync automatically. Two triggers share one updater
# script with a 7-day timestamp guard:
#   1. weekly cron (Mondays 09:00) for machines that are on at that time
#   2. shell startup (bashrc/zshrc) as catch-up — if the PC was off when cron
#      would have fired, the update runs the next time a terminal opens
# The guard means at most one real update per 7 days no matter how many
# terminals open; a failed update (e.g. offline) retries on the next trigger.
NPX_BIN="$(command -v npx)"
UPDATER="${HOME}/.claude/skills-auto-update.sh"
mkdir -p "${HOME}/.claude"
cat > "${UPDATER}" <<UPDEOF
#!/usr/bin/env bash
# Auto-generated by my-claude-skills bootstrap. Updates global Claude skills
# at most once every 7 days; pass --force to ignore the timestamp guard.
STAMP="\${HOME}/.claude/.skills-last-update"
NOW=\$(date +%s)
LAST=\$(cat "\${STAMP}" 2>/dev/null || echo 0)
if [ "\${1:-}" = "--force" ] || [ \$((NOW - LAST)) -ge 604800 ]; then
  # Re-add (idempotent) rather than 'skills update': update -g has been
  # observed to silently skip refreshing changed skills from this repo,
  # while add always syncs to current main.
  if ${NPX_BIN} --yes skills add "${REPO}" -s '*' -g -y >/dev/null 2>&1; then
    echo "\${NOW}" > "\${STAMP}"
  fi
fi
UPDEOF
chmod +x "${UPDATER}"
echo "==> Wrote updater to ${UPDATER}"

if command -v crontab >/dev/null 2>&1; then
  CRON_TAG="# my-claude-skills-auto-update"
  if ! crontab -l 2>/dev/null | grep -qF "${CRON_TAG}"; then
    (crontab -l 2>/dev/null; echo "0 9 * * 1 ${UPDATER} --force >/dev/null 2>&1 ${CRON_TAG}") | crontab -
    echo "==> Added weekly auto-update cron (Mondays 09:00)"
  else
    echo "==> Weekly auto-update cron already present"
  fi
else
  echo "==> crontab not available — relying on shell-startup catch-up only"
fi

# Shell-startup catch-up: appended to both bash and zsh rc files (created if
# missing), guarded by a marker so bootstrap re-runs never duplicate it. Runs
# the updater silently in the background; the 7-day guard makes it a no-op on
# almost every shell start.
RC_MARKER="# my-claude-skills:auto-update-catchup"
for RC in "${HOME}/.bashrc" "${HOME}/.zshrc"; do
  if ! grep -qF "${RC_MARKER}" "${RC}" 2>/dev/null; then
    {
      echo ""
      echo "${RC_MARKER}"
      echo "[ -x \"\$HOME/.claude/skills-auto-update.sh\" ] && (\"\$HOME/.claude/skills-auto-update.sh\" >/dev/null 2>&1 &)"
    } >> "${RC}"
    echo "==> Added startup catch-up to ${RC}"
  else
    echo "==> Startup catch-up already present in ${RC}"
  fi
done

echo ""
echo "Done. $(ls -1 "${HOME}/.claude/skills" 2>/dev/null | wc -l | tr -d ' ') entries now in ~/.claude/skills."
echo "New skills are picked up the next time you start a Claude Code session."
