#!/usr/bin/env bash
# Bootstrap this machine with all skills from spiosifidis/my-claude-skills.
#
# Usage (run on any new or existing machine):
#   curl -fsSL https://raw.githubusercontent.com/spiosifidis/my-claude-skills/main/bootstrap.sh | bash
# or, from a local clone:
#   ./bootstrap.sh
#
# Idempotent: safe to re-run any time; re-running also picks up new/updated skills.
set -euo pipefail

REPO="spiosifidis/my-claude-skills"

if ! command -v npx >/dev/null 2>&1; then
  echo "error: npx not found — install Node.js first (https://nodejs.org)" >&2
  exit 1
fi

echo "==> Installing/syncing all skills from ${REPO} into user scope (~/.claude/skills)..."
# Two separate bugs, both confirmed on a real curl | bash run, live here:
#
# 1. stdin theft (the actual root cause of the whole script silently dying
#    after this line, every time, on a real machine — reproduced with a stub
#    npx that reads one line from its inherited stdin). When this script
#    arrives via `curl | bash`, this process's stdin IS the live pipe bash is
#    still reading the rest of the script from. The skills CLI's TUI
#    (spinners/prompts) can read from its inherited stdin even with -y/--yes
#    passed, which silently steals the NEXT LINE of this script out of bash's
#    parsing stream — in the reproduction, that was the `if [ ! -d ... ];
#    then` line just below, orphaning the `echo error / exit 1` inside it so
#    they ran unconditionally as top-level statements. `< /dev/null` detaches this
#    process's stdin from the shared pipe entirely, so it hits EOF instantly
#    instead of reading live script bytes.
#
# 2. non-zero exit on partial success. The skills CLI targets many agents
#    (Claude Code, Codex, PromptScript, ...) and exits non-zero whenever ANY
#    per-agent target fails — including expected, benign ones (an agent that
#    doesn't support global installs at all). Under `set -e` that would kill
#    the rest of this script too. `|| true` defers to the real check just
#    below instead: a genuine total failure (network down, repo unreachable)
#    is still caught there, but a benign partial failure isn't fatal.
npx --yes skills add "${REPO}" -s '*' -g -y < /dev/null || true
if [ ! -d "${HOME}/.claude/skills" ] || [ -z "$(ls -A "${HOME}/.claude/skills" 2>/dev/null)" ]; then
  echo "error: no skills were installed to ~/.claude/skills — check the output above for the cause (network, auth, or a missing 'npx')." >&2
  exit 1
fi

# Make skill invocation reliable: a one-line nudge in the global CLAUDE.md so
# every session checks installed skills before answering. Guarded so re-runs
# never duplicate it.
CLAUDE_MD="${HOME}/.claude/CLAUDE.md"
MARKER="<!-- my-claude-skills:invoke-skills -->"
if ! grep -qF "${MARKER}" "${CLAUDE_MD}" 2>/dev/null; then
  mkdir -p "${HOME}/.claude"
  {
    echo ""
    echo "${MARKER}"
    echo "Before responding to any request, check whether an installed skill in ~/.claude/skills applies (see the using-superpowers skill). If one plausibly applies, invoke it with the Skill tool before doing anything else."
  } >> "${CLAUDE_MD}"
  echo "==> Added skill-invocation reminder to ${CLAUDE_MD}"
else
  echo "==> Skill-invocation reminder already present in ${CLAUDE_MD}"
fi

# Keep this machine in sync automatically. Two triggers share one updater
# script with a 7-day timestamp guard:
#   1. weekly cron (Mondays 09:00) for machines that are on at that time
#   2. shell startup (bashrc/zshrc) as catch-up — if the PC was off when cron
#      would have fired, the update runs the next time a terminal opens
# The guard means at most one real update per 7 days no matter how many
# terminals open; a failed update (e.g. offline) retries on the next trigger.
# The updater additionally refuses to sync while a Claude Code session is
# running (the sync deletes-and-recreates skill dirs, which makes skills
# vanish mid-session) and skips entirely when the repo hasn't changed.
NPX_BIN="$(command -v npx)"
UPDATER="${HOME}/.claude/skills-auto-update.sh"
mkdir -p "${HOME}/.claude"
cat > "${UPDATER}" <<UPDEOF
#!/usr/bin/env bash
# Auto-generated by my-claude-skills bootstrap. Updates global Claude skills
# at most once every 7 days; pass --force to ignore the timestamp guard.
STAMP="\${HOME}/.claude/.skills-last-update"
SHA_FILE="\${HOME}/.claude/.skills-last-sha"
NOW=\$(date +%s)
LAST=\$(cat "\${STAMP}" 2>/dev/null || echo 0)
if [ "\${1:-}" != "--force" ] && [ \$((NOW - LAST)) -lt 604800 ]; then
  exit 0
fi

# NEVER sync while a Claude Code session is live: the skills CLI
# deletes-and-recreates skill directories during the sync, so a running
# session watches its skills vanish mid-conversation. Defer instead —
# the stamp stays unwritten, so the next terminal-open retries.
# (Deliberately narrow patterns: a bare -f "claude" would match this
# script's own ~/.claude/... path.)
if pgrep -x claude >/dev/null 2>&1 || pgrep -f "claude-code/cli" >/dev/null 2>&1; then
  exit 0
fi

# Skip the churn entirely when the repo hasn't changed since last sync —
# a full 58-skill re-add for zero updates is all risk, no benefit.
REMOTE_SHA=\$(git ls-remote "https://github.com/${REPO}" main 2>/dev/null | cut -f1)
if [ -n "\${REMOTE_SHA}" ] && [ "\${REMOTE_SHA}" = "\$(cat "\${SHA_FILE}" 2>/dev/null)" ]; then
  echo "\${NOW}" > "\${STAMP}"
  exit 0
fi

# Re-add (idempotent) rather than 'skills update': update -g has been
# observed to silently skip refreshing changed skills from this repo,
# while add always syncs to current main.
if ${NPX_BIN} --yes skills add "${REPO}" -s '*' -g -y >/dev/null 2>&1; then
  echo "\${NOW}" > "\${STAMP}"
  [ -n "\${REMOTE_SHA}" ] && echo "\${REMOTE_SHA}" > "\${SHA_FILE}"
fi
UPDEOF
chmod +x "${UPDATER}"
echo "==> Wrote updater to ${UPDATER}"

# Weekly health check ("doctor"): verifies skills are installed and synced,
# catches the failure modes that have actually happened (broken skill
# symlinks, root-owned ~/.agents, stale sync, local-only skills not backed
# up), and raises a macOS notification only when something is wrong. The
# script itself ships as the claude-doctor skill so the sync keeps it
# current; runs 30 min after the updater so it checks the freshly-synced
# state. Run manually any time:
#   bash ~/.claude/skills/claude-doctor/scripts/doctor.sh
DOCTOR="${HOME}/.claude/skills/claude-doctor/scripts/doctor.sh"

if command -v crontab >/dev/null 2>&1; then
  CRON_TAG="# my-claude-skills-auto-update"
  if ! crontab -l 2>/dev/null | grep -qF "${CRON_TAG}"; then
    (crontab -l 2>/dev/null; echo "0 9 * * 1 ${UPDATER} --force >/dev/null 2>&1 ${CRON_TAG}") | crontab -
    echo "==> Added weekly auto-update cron (Mondays 09:00)"
  else
    echo "==> Weekly auto-update cron already present"
  fi
  DOCTOR_TAG="# my-claude-skills-doctor"
  if ! crontab -l 2>/dev/null | grep -qF "${DOCTOR_TAG}"; then
    (crontab -l 2>/dev/null; echo "30 9 * * 1 [ -f \"${DOCTOR}\" ] && bash \"${DOCTOR}\" --auto >/dev/null 2>&1 ${DOCTOR_TAG}") | crontab -
    echo "==> Added weekly health-check cron (Mondays 09:30)"
  else
    echo "==> Weekly health-check cron already present"
  fi
else
  echo "==> crontab not available — relying on shell-startup catch-up only"
fi

# Shell-startup catch-up: appended to both bash and zsh rc files (created if
# missing), guarded by a marker so bootstrap re-runs never duplicate it. Runs
# the updater silently in the background; the 7-day guard makes it a no-op on
# almost every shell start.
RC_MARKER="# my-claude-skills:auto-update-catchup"
for RC in "${HOME}/.bashrc" "${HOME}/.zshrc"; do
  if ! grep -qF "${RC_MARKER}" "${RC}" 2>/dev/null; then
    {
      echo ""
      echo "${RC_MARKER}"
      echo "[ -x \"\$HOME/.claude/skills-auto-update.sh\" ] && (\"\$HOME/.claude/skills-auto-update.sh\" >/dev/null 2>&1 &)"
    } >> "${RC}"
    echo "==> Added startup catch-up to ${RC}"
  else
    echo "==> Startup catch-up already present in ${RC}"
  fi
done

# Same catch-up for the weekly doctor: if the Mac was off Monday morning,
# the check runs the next time a terminal opens. Its own 7-day stamp guard
# makes this a no-op on almost every shell start; --auto is silent except
# for a macOS notification when problems are found.
DOCTOR_RC_MARKER="# my-claude-skills:doctor-catchup"
for RC in "${HOME}/.bashrc" "${HOME}/.zshrc"; do
  if ! grep -qF "${DOCTOR_RC_MARKER}" "${RC}" 2>/dev/null; then
    {
      echo ""
      echo "${DOCTOR_RC_MARKER}"
      echo "[ -f \"\$HOME/.claude/skills/claude-doctor/scripts/doctor.sh\" ] && (bash \"\$HOME/.claude/skills/claude-doctor/scripts/doctor.sh\" --auto >/dev/null 2>&1 &)"
    } >> "${RC}"
    echo "==> Added health-check catch-up to ${RC}"
  else
    echo "==> Health-check catch-up already present in ${RC}"
  fi
done

echo ""
echo "Done. $(ls -1 "${HOME}/.claude/skills" 2>/dev/null | wc -l | tr -d ' ') entries now in ~/.claude/skills."
echo "New skills are picked up the next time you start a Claude Code session."
